### ISSUE TITLE
High CPU Usage of core.NewCoffer

### ISSUE THREAD

**Issue by pzeinlinger** [awnumar/memguard#100]
**Describe the bug**
I noticed high cpu usage (0.1 became >2%) of my service after adding memguard.
Although no active memguard.Buffer is in use, the cpu usage is noticably higher.
I guess it has something to do with core.Coffer's Rekey routine.

**To Reproduce**
You can clone my test repo from gitlab.com/pzeinlinger/memguardcputest
It starts a webserver and only opens the enclave when a request is made.

**Screenshots**
![pprof](https://user-images.githubusercontent.com/26354635/61593662-d968e680-abe2-11e9-8747-db606e6908bd.png)
![htop](https://user-images.githubusercontent.com/26354635/61593666-e5ed3f00-abe2-11e9-8879-43a3a34e6da1.png)

**System (please complete the following information):**
 - OS and Kernel Versions:  4.19.59-1-MANJARO
 - Memguard Version: 0.17.3

**Comment by awnumar** [comment]
Thanks for the report.

Those CPU numbers seem reasonable to me but I have pushed a [branch](https://github.com/awnumar/memguard/tree/interval) with a function allowing the caller to update the interval. The default is 8 milliseconds. I would keep your choice below 1000ms.

Could you test with a different interval to see if the change resolves the issue for you?

**Comment by pzeinlinger** [comment]
Thank you! Much better. Would you consider a higher interval a security risk?

**Comment by awnumar** [comment]
The choice of the interval value is the classic security/performance trade-off. A lower interval is _better_ but any low value should be sufficient. The original [source](https://spacetime.dev/memory-retention-attacks) states a value of 1 second.

By "much better" I assume you mean you've tested the change? What kind of loads are you now getting for what choice of interval value?

**Comment by pzeinlinger** [comment]
Using 1 second results in no apparent increase of cpu usage compared to a project without memgurad.

**Comment by awnumar** [comment]
Great. It might be worth looking into the lowest such value that results in no noticeable load.
