### ISSUE TITLE
proposal: API change: export normal functions instead of methods

### ISSUE THREAD

**Issue by nsajko** [awnumar/memguard#109]
Memguard currently exports a lot of methods, almost none of which are associated with interfaces. It would thus probably be good to replace the methods in Memguard with the usual functions, because of the performance overhead of methods.

Note that this does not conflict with https://github.com/awnumar/memguard/issues/68 , as additional methods to implement io interfaces can be added later.

**Comment by awnumar** [comment]
Can you give an example?

Do you mean, for example, replacing `func (*LockedBuffer) Bytes() []byte` with `func Bytes(*LockedBuffer) []byte`?

**Comment by nsajko** [comment]
Yes.

**Comment by awnumar** [comment]
I have serious doubts that would impact performance in a significant way, especially relative to the heavy lifting being done within the methods themselves. I am happy to be proven wrong, but the benefits would have to outweigh the loss of ergonomics and the breaking change to facilitate them.

 > almost none of which are associated with interfaces

Why is this of note?

**Comment by nsajko** [comment]
I might be misremembering that whole "methods have performance overhead relative to non-receiver functions" thing, sorry. I thought that there is additional run time indirection associated with method calls, but after searching the web I can not find any mention of that and I can not be bothered to check the assembly currently, so I am closing the issue, at least for now.

**Comment by nsajko** [comment]
BTW, what I am sure of is that interfaces have a run-time cost, but that does not matter for Memguard.
