### ISSUE TITLE
C API/C equivalent?

### ISSUE THREAD

**Issue by ethindp** [awnumar/memguard#122]
Would it be possible for this library to export a C/C++ API, or is there a C/C++ equivalent to this library?

**Comment by awnumar** [comment]
There's no current plans for that but apparently it's [possible](https://medium.com/learning-the-go-programming-language/calling-go-functions-from-other-languages-4c7d8bcc69bf) to do this yourself.

[libsodium](https://github.com/jedisct1/libsodium) also implements a guarded heap allocator.
