### ISSUE TITLE
NewImmutableFromBytes() was deprecated?

### ISSUE THREAD

**Issue by robertwilliamallen** [awnumar/memguard#139]
I'm working with another project that was using memguard but `NewImmutableFromBytes()` is missing from the latest version of memguard (as far as I can see). Can someone show me how to patch this with similar functionality using existing memguard primitives?

**Comment by awnumar** [comment]
LockedBuffers that are initialised with data at creation time are immutable by default. So the NewBufferFromBytes function is equivalent.
