### ISSUE TITLE
[Question] Does memguard protect against bit flips caused by cosmic rays?

### ISSUE THREAD

**Issue by 1366613** [awnumar/memguard#146]

**Comment by prologic** [comment]
Isn't that what ECC Memory is for? 😆

**Comment by prologic** [comment]
I think memguard's use case is different

**Comment by awnumar** [comment]
Memguard doesn't implement any specific detection or correction for bit flips. It may detect a bit flip if it happened in the canary region of a Buffer, or to the ciphertext in an Enclave, but this would result in a crash 

As @prologic said, bit flips are not something Memguard aims to handle
