### ISSUE TITLE
Nil pointer panic before main function call 

### ISSUE THREAD

**Issue by papazloynt** [awnumar/memguard#150]
Hello, I am using in my project an imported module ```github.com/awnumar/fastrand``` which uses indirect as a dependency on the ```github.com/awnumar/memguard``` package. My project works well when launching the release version, but as soon as I switch to debug mode, my program crashes with a panic until the main function is called, here is the error images: .
### error occurs right here
![find error ocuring code](https://github.com/awnumar/memguard/assets/41233824/9aa69913-6832-41f4-b1e3-87348b678f66)
### panic info
![panic info](https://github.com/awnumar/memguard/assets/41233824/c9b2264a-1613-4649-82f3-f23039d560a4)

 But when I run my program with sudo in debug mode, everything works fine like in relese mode. Please tell me if this is a bug or a feature and what could be the reason for this behavior.
I came across similar issues related to [benchmarks](https://github.com/awnumar/memguard/issues/119) and [telegraph](https://github.com/awnumar/memcall/issues/3), but none of the solutions helped me. I would be grateful if you could help me solve my problem, thanks in advance!

**Comment by awnumar** [comment]
This is most likely because debug mode prevents Mlock. Unfortunately memguard doesn't currently support disabling Mlock
