### ISSUE TITLE
build fails on AIX

### ISSUE THREAD

**Issue by jtroy** [awnumar/memguard#154]
**Describe the bug**
memguard doesn't build on AIX because of missing support in `github.com/awnumar/memcall`.

**To Reproduce**
Steps to reproduce the behaviour:
1. `build ./...` either on AIX or cross-compile with GOOS=aix GOARCH=ppc64
2. See error:

```
bash-4.4$ go build ./...
go: downloading lukechampine.com/frand v1.4.2
go: downloading github.com/awnumar/memcall v0.1.2
go: downloading golang.org/x/crypto v0.13.0
go: downloading github.com/aead/chacha20 v0.0.0-20180709150244-8b13a72661da
go: downloading golang.org/x/sys v0.12.0
# github.com/awnumar/memcall
../../go/pkg/mod/github.com/awnumar/memcall@v0.1.2/memcall_unix.go:15:23: undefined: unix.MADV_DONTDUMP
```

**Expected behaviour**
build succeeds without error

**System (please complete the following information):**
 - OS and Kernel Versions: AIX 7.2 on POWER 9
 - Memguard Version: master (f8a2722)
 - Go Version: go version go1.21.0 aix/ppc64

**Additional context**
I ended up here because I'm trying to build telegraf, which depends on memguard, for AIX. I've submitted a [PR to add AIX support to memcall](https://github.com/awnumar/memcall/pull/11). This makes the build succeed. I will follow up with test results.

Thanks,
John

**Comment by awnumar** [comment]
Thanks for the PR!

Does the casting test only fail for you on AIX or in general?

**Comment by awnumar** [comment]
Closing because of https://github.com/awnumar/memguard/commit/78a7ad6afa56e665c0e183d68f05601cc551e798
