### ISSUE TITLE
application crash when using b.Buffer.Data() (or any []byte return)

### ISSUE THREAD

**Issue by RRancio** [awnumar/memguard#164]
im not sure if maybe is code issue, but i tried everything to make Memguard actually return the []byte variable in order to use it, video bellow.

im not sure if i maybe forgot to unlock, init or enable something but i didn't manage it to work, but it prints the content that i want to be returned
https://streamable.com/3dzpmi
same video but imgur: [video](https://i.imgur.com/9SgaDcw.mp4)

edit: i tried also using *memguard.Enclave but gives the same "crash"

**Comment by awnumar** [comment]
Could you post a minimal reproducing program that also has the problem?

**Comment by awnumar** [comment]
This is likely caused by the system limitation on the working set size for VirtualLock: https://learn.microsoft.com/en-us/windows/win32/api/memoryapi/nf-memoryapi-virtuallock

Perhaps try to break down your data into chunks.

**Comment by awnumar** [comment]
No, you have just instructed the kernel to raise your limit for the process. By the way, that syscall is available as a function here: https://pkg.go.dev/golang.org/x/sys/windows#SetProcessWorkingSetSizeEx
