### ISSUE TITLE
Is PROT_EXEC required?

### ISSUE THREAD

**Issue by anitgandhi** [awnumar/memguard#37]
Looking at this code: https://github.com/awnumar/memguard/blob/79d54e0bde799a6e8285546a0ae53383fc796103/memcall/memcall_unix.go#L52-L57

Is PROT_EXEC really required? It feels unnecessary given the use case of memguard for byte slices only.

**Comment by awnumar** [comment]
It was originally added _just in case_, since I wasn't aware of Go's own mmap policies. I'm currently working on a refactor of the 'memcall' package---amongst other things---that will remove it.

I guess this issue is a good as place as any to track progress.
