### ISSUE TITLE
MADV_DONTDUMP and MAP_ANONYMOUS do not exist on OpenBSD amd64

### ISSUE THREAD

**Issue by stephane-martin** [awnumar/memguard#45]
Hello,

compilation fails on OpenBSD because MADV_DONTDUMP and MAP_ANONYMOUS do not exist in golang/x/sys/unix.

- MADV_DONTDUMP is not actually supported by OpenBSD => should be dropped there
- MAP_ANONYMOUS *shoud* exist, but strangely golang/x/sys/unix does not have it on amd64. But MAP_ANON is there (???) and can be used.
- 0x00020000 does not exist on OpenBSD

Thanks!

**Comment by awnumar** [comment]
I have [created a patch](https://go-review.googlesource.com/c/sys/+/78595) against `sys/unix` that adds the `MAP_ANONYMOUS` flag to the set of OpenBSD constants.
