### ISSUE TITLE
Missing function WipeBytes

### ISSUE THREAD

**Issue by bionoren** [awnumar/memguard#58]
The documentation for *LockedBuffer.Copy says "You should aim to call WipeBytes on the original slice as soon as possible". However, there is no such function in this library or in the standard library. It sounds like a useful function though. Can you implement it? Or update the documentation to not reference it or to recommend something else?

**Comment by awnumar** [comment]
Ah that's an oversight on my part. There did used to be a WipeBytes
function but it was removed. I'm not sure now if I should re-add it or just
update the documentation, but I'll have a think about it.

Thanks for reporting this!
