### ISSUE TITLE
Implement io.Reader, io.Writer, etc.

### ISSUE THREAD

**Issue by au-phiware** [awnumar/memguard#68]
**Is your feature request related to a problem? Please describe.**
Some APIs that work with sensitive data use the `io` interfaces, e.g. [`openpgp.ReadKeyRing`](https://godoc.org/golang.org/x/crypto/openpgp#ReadKeyRing) and [`openpgp.(*Entity).SerializePrivate`](https://godoc.org/golang.org/x/crypto/openpgp#Entity.SerializePrivate).

**Describe the solution you'd like**
It would be easier to use memguard if `LockedBuffer` implemented these interfaces. Particularly for `io.Writer`, since in this case the `LockedBuffer` could handle growing the buffer as needed.

**Describe alternatives you've considered**
At the moment I work around this issue by wrapping `LockedBuffer.Buffer()` in a `bytes.Buffer`. However, this causes a problem when the buffer needs to grow.

**Comment by awnumar** [comment]
The growing of the buffer will always be difficult (see [here](https://cryptolosophy.org/memory-security-go/)) unless I can come up with a way to do it seamlessly. I think currently the only way to do it in memguard is by creating a new container of the appropriate size, moving the data, and then destroying the old container.

**Comment by au-phiware** [comment]
I've read that article previously; it's very interesting. I figured that a new buffer would need to be allocated and all the contents copied across. I think the cost is appropriate for the benefit.

Prevention is better than cure in this case. For me I'll know the required buffer size 99% of the time I just want something to cover that 1%.

**Comment by awnumar** [comment]
An easy solution for this would be for me to just add a single new method. Something like,

```go
// Grow increases the size of an Enclave by a given number of bytes.
func (b *Enclave) Grow(n int) (*Enclave, error) {}
```

**Comment by awnumar** [comment]
I committed a Resize method for LockedBuffer objects:

https://github.com/awnumar/memguard/blob/5583953cd753b3514fa3fadede797568c6f14549/buffer.go#L170-L195

Is this sufficient? If not, please explain why.
